name: "Run Markdownlint"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout: Uso de la acción oficial actions/checkout@v4 [cite: 67]
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Markdown Lint: Revisión de sintaxis [cite: 68]
      - name: "Run Markdownlint"
        uses: davidanson/markdownlint-cli2-action@v16
        with:
          # Busca el archivo .markdownlint.json solicitado [cite: 82]
          config: '.markdownlint.json'
          # Revisa todos los archivos markdown [cite: 84]
          globs: '**/*.md'