name: "Revision de MarkDown"

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  markdownlint:
    name: "Check Documentation Quality"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      # Esta es la sección del error (Línea 15 aprox.)
      - name: "Run Markdownlint"
        uses: davidanson/markdownlint-cli2-action@v16
        with:
          config: '.markdownlint.json'
          globs: '**/*.md'

      - name: "Aprobacion de Actions"
        run: echo "Revision de MarkDown finalizada con exito. Documentacion aprobada."